# Generated by Django 3.0.2 on 2020-02-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200224_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-food.jpg', upload_to='post_pics'),
        ),
    ]
