# Generated by Django 3.0.2 on 2020-02-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default-food.jpg', upload_to='post_pics'),
        ),
    ]
